---
- name: Configure servers
  hosts: all
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - configure-server
    - configure-prometheus-node-exporter
