---
- name: Configure servers
  hosts: all
  user: ubuntu
  vars:
    - ansible_python_interpreter: /usr/bin/python3 # python interpreter error fix, Unhandled error in Python interpreter discovery for host
    - ansible_host_key_checking: false # no yes/no prompt for keyprint
    - ansible_stdout_callback: yaml
  roles:
    - configure-server
    - configure-prometheus-node-exporter
