version: 2.1

jobs:
  # hello-world:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Say Hello
  #         command: |
  #           echo "Hello World"
  backend-build: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run:
          name: Backend Build
          command: |
            ls
            cd backend
            npm ci
            npm run build
      # - save_cache: 
      #     key: backend-{{ checksum "package-lock.json" }}
      #     paths: 
      #       - backend/node_modules
  backend-test: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      # - restore_cache: 
      #     keys: backend-{{ checksum "/backend/package-lock.json" }}  
      - run:
          name: Run Backend tests with JUnit as reporter
          command: |
            cd backend
            npm ci
            npm t -- --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
      - run:
          name: Backend Tests failed
          command: |
            echo "Backend tests have failed, placeholder for later"
          when: on_fail
  backend-npmaudit: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run: 
          name: Audit npm packages
          command: |
            cd backend
            npm audit --audit-level=critical   
            
  frontend-build: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run:
          name: Frontend Build
          command: |
            cd frontend
            npm ci
            npm run build
      # - save_cache: 
      #     key: frontend-{{ checksum "./frontend/package-lock.json" }}
      #     paths: 
      #       - frontend/node_modules
  frontend-test: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      # - restore_cache: 
      #     keys: frontend-{{ checksum "./frontend/package-lock.json" }}  
      - run:
          name: Run frontend tests with JUnit as reporter
          command: |
            cd frontend
            npm ci
            npm t -- --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
      - run:
          name: frontend Tests failed
          command: |
            echo "frontend tests have failed, placeholder for later"
          when: on_fail
  frontend-npmaudit: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run: 
          name: Audit npm packages
          command: |
            cd frontend
            npm audit --audit-level=critical   
workflows:
  default:
    jobs:
      # - hello-world
      - frontend-npmaudit
      - backend-npmaudit
      - backend-build:
          requires: 
            - backend-npmaudit
      - frontend-build:
          requires: 
            - frontend-npmaudit
      - backend-test:
          requires: 
            - backend-build
      - frontend-test:
          requires: 
            - frontend-build
