version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"
  backend-build: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run:
          name: Backend Build
          command: |
            ls
            cd backend
            npm install
            npm run build   
      - run:
          name: Run Backend tests with JUnit as reporter
          command: npm t -- --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
      - run:
          name: Backend Tests failed
          command: |
            echo "Backend tests have failed, placeholder for later"
          when: on_fail

            
  frontend-build: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run:
          name: Frontend Build
          command: |
            cd frontend
            npm install
            npm run build
      - run:
          name: Run Frontend tests with JUnit as reporter
          command: npm t -- --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
      - run:
          name: Frontend Tests failed
          command: |
            echo "Frontend tests have failed, placeholder for later"
          when: on_fail
workflows:
  default:
    jobs:
      - hello-world
      - backend-build
      - frontend-build
